In [41]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

# para rodar o chrome em 2º plano
# from selenium.webdriver.chrome.options import Options
# chrome_options = Options()
# chrome_options.headless = True 
# navegador = webdriver.Chrome(options=chrome_options)

# abrir o navegador
navegador = webdriver.Chrome()
navegador.get('https://www.google.com/')

# cotação dólar

navegador.find_element(By.XPATH,
                       '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação do dólar')
navegador.find_element(By.XPATH, 
                       '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cotacao_dolar = navegador.find_element(By.XPATH,
                                      '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')

# cotação euro
navegador.get('https://www.google.com/')
navegador.find_element(By.XPATH,
                       '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação do euro')
navegador.find_element(By.XPATH, 
                       '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
cotacao_euro = navegador.find_element(By.XPATH,
                                      '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')

# cotação ouro

navegador.get('https://www.melhorcambio.com/ouro-hoje')
cotacao_ouro = navegador.find_element(By.XPATH,
                      '//*[@id="comercial"]').get_attribute('value')
cotacao_ouro = cotacao_ouro.replace(',', '.')


navegador.quit()

# importar tabela de produtos

import pandas as pd

tabela = pd.read_excel("C:/Users/junin/Downloads/Produtos.xlsx")

# recalcular o preço de cada produto 
# atualizar a cotação
# nas linhas onde na coluna 'moenda' - 'dólar'

tabela.loc[tabela['Moeda'] == 'Dólar', 'Cotação'] = float(cotacao_dolar)
tabela.loc[tabela['Moeda'] == 'Euro', 'Cotação'] = float(cotacao_euro)
tabela.loc[tabela['Moeda'] == 'Ouro', 'Cotação'] = float(cotacao_ouro)

# atualizar o preço base reais (preço base original * cotação)
tabela['Preço de Compra'] = tabela['Preço Original'] * tabela['Cotação']

# atualizar o preço final (preço base reais * margem)
tabela['Preço de Venda'] = tabela['Preço de Compra'] * tabela['Margem']


display(tabela)

# salvar o dados atualizados e exportar para base em excel no computador

tabela.to_excel("C:/Users/junin/Downloads/Produtos Novo.xlsx", index=False)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.076400,5076.349236,1.40,7106.888930
1,Carro Renault,4500.00,Euro,5.209681,23443.563969,2.00,46887.127938
2,Notebook Dell,899.99,Dólar,5.076400,4568.709236,1.70,7766.805701
3,IPhone,799.00,Dólar,5.076400,4056.043600,1.70,6895.274120
4,Carro Fiat,3000.00,Euro,5.209681,15629.042646,1.90,29695.181027
5,Celular Xiaomi,480.48,Dólar,5.076400,2439.108672,2.00,4878.217344
6,Joia 20g,20.00,Ouro,296.640000,5932.800000,1.15,6822.720000